// Partea a doua a dictionarului: etichete, jurnal, hero, promo, pagina Calitate.
// Traduse manual, la fel ca in traduceri-db.mjs.

export const TAGURI = {
  'Bestseller': 'Bestseller',
  'Transport Gratuit': 'Free Shipping',
  'Produs Nou': 'New Product',
  'Nou': 'New',
  'Pentru Femei': 'For Women',
  'Super Preț': 'Great Price',
  '-15%': '-15%',
  '-10%': '-10%',
  '-15% Extra': 'Extra -15%',
  '-10% Extra': 'Extra -10%',
  'Premium': 'Premium',
  'Limitat': 'Limited',
};

export const AUTOR_JURNAL = {
  'Echipa Medicală Longevity Pharma': 'The Longevity Pharma Medical Team',
};

export const TAGURI_JURNAL = {
  'Biohacking': 'Biohacking',
  'Anti-aging': 'Anti-aging',
  'NMN': 'NMN',
  'Ingrediente': 'Ingredients',
  'Nutriție': 'Nutrition',
  'Articulații': 'Joints',
  'Protocoale': 'Protocols',
  'Imunitate': 'Immunity',
  'Stil de viață': 'Lifestyle',
  'Calitate': 'Quality',
  'Transparență': 'Transparency',
};

// Articolele de jurnal, pe slug. Slug-urile raman neschimbate ca sa nu se
// rupa linkurile deja generate; se traduc titlul, sumarul si continutul.
export const JURNAL = {
  'cum-functioneaza-nmn-ul-la-nivel-celular': {
    title: 'How NMN works at the cellular level to delay aging',
    summary: 'Nicotinamide mononucleotide (NMN) has captured the attention of the scientific world. Find out how it restores NAD+ levels and directly influences longevity.',
    content: `NAD+ (Nicotinamide Adenine Dinucleotide) is an essential coenzyme present in every living cell, responsible for energy production and DNA repair. As we grow older, NAD+ levels fall dramatically, setting off the processes of cellular aging.

NMN is the direct precursor of NAD+. Recent clinical studies show that supplementing with pure, pharmaceutical-grade NMN can raise the body's NAD+ reserves quickly and efficiently. This reactivates the sirtuins (the so-called "longevity genes"), improves mitochondrial function and protects the integrity of the genome.

At Longevity Pharma we chose a formula with a purity of >99%, because unstable or impure NMN molecules can degrade into plain nicotinamide and lose their anti-aging properties.`,
  },

  'colagen-hidrolizat-vs-colagen-nativ': {
    title: 'Hydrolyzed collagen vs. native collagen: what do the clinical studies say?',
    summary: 'The difference between the types of collagen determines how effective they are. Discover why molecular weight is the single most important factor in absorption.',
    content: `The supplement market is flooded with all kinds of collagen formulas, yet few consumers know how much molecular mass matters. Native collagen, excellent though it is in theory, has a molecule too large to cross the intestinal barrier intact.

The enzymatic hydrolysis process used in modern laboratories turns raw collagen into peptides of microscopic size (under 2000 Daltons). This hydrolyzed form of collagen is absorbed into the bloodstream at a rate of over 90%, reaching the fibroblasts that synthesize new connective tissue for the skin, the joints and the blood vessels.

Our recommendation is a hydrolyzed marine collagen from sustainable sources, whose bioavailability exceeds that of bovine or porcine versions.`,
  },

  'protocol-reducere-inflamatie-stres-oxidativ': {
    title: 'A complete protocol for reducing inflammation and oxidative stress',
    summary: 'Chronic low-grade inflammation is the source of most modern conditions. Here is the daily protocol validated by experts for fighting it.',
    content: `Silent or chronic inflammation shows no immediate symptoms, yet over time it damages tissue and accelerates cellular senescence. The oxidative stress generated by free radicals is the main engine of this kind of inflammation.

The protocol our experts propose involves a three-step approach:
1. **Neutralizing free radicals:** taking powerful antioxidants such as resveratrol or glutathione, which donate electrons to unstable molecules without becoming harmful themselves.
2. **Modulating the immune response:** optimizing vitamin D3 and zinc levels, both essential for a balanced immune system that does not overreact.
3. **Lowering inflammatory markers:** introducing high-purity omega-3 fatty acids (with an optimal EPA/DHA ratio) to bring down the level of pro-inflammatory cytokines.

Supplementation should be paired with sunlight exposure in the first hours of the morning and at least 7 hours of restorative sleep.`,
  },

  'testare-lot-productie-laborator-tert': {
    title: 'Why we test every production batch in a third-party laboratory',
    summary: 'Quality is not declared, it is demonstrated. Find out what independent laboratory testing involves and why it is essential for your safety.',
    content: `The food supplement industry is often a gray area when it comes to strict regulation. Many manufacturers rely solely on the certificate of analysis issued by the supplier of the raw material - a practice prone to errors and inaccuracies.

At Longevity Pharma we apply the "Trust, but Verify" standard. Every batch of finished product is sent to an independent laboratory (third-party testing) for analysis. What exactly are we looking for?
- **Identity and potency:** we make sure there really are 500mg of the active substance declared on the label, not 450mg and not a similar chemical compound.
- **Microbiology:** we check for the absence of dangerous bacteria, molds and yeasts.
- **Heavy metals:** we test for lead, mercury, cadmium and arsenic, using extremely strict standards (USP/EP).

Only the products that pass this "gold filter" reach you, guaranteeing you maximum efficacy and zero risk.`,
  },
};

// Slide-urile din carusel, cheia este titlul romanesc.
export const HERO = {
  'Investește Astăzi în Ziua de Mâine': {
    label: 'Bestseller',
    title: 'Invest Today in Your Tomorrow',
    description: 'Premium food supplements, scientifically formulated for cellular longevity and everyday vitality.',
  },
  'Extracte Naturale, Puritate Maximă': {
    label: 'New',
    title: 'Natural Extracts, Maximum Purity',
    description: 'Essential nutrients from organic plants with maximum bioavailability. No allergens, no compromises.',
  },
  'Știință și Inovație Pentru Longevitate': {
    label: 'Quality',
    title: 'Science and Innovation for Longevity',
    description: 'Every batch tested in independent laboratories. Total transparency, guaranteed quality.',
  },
};

export const PROMO = {
  'Pachetul de Longevitate': {
    title: 'The Longevity Bundle',
    description: 'NMN + Resveratrol. The perfect combination for slowing cellular aging, at 15% off.',
    tag: '15% OFF',
  },
};

// Pagina Calitate & Ingrediente, cheia este section_key.
export const CALITATE = {
  hero: {
    label: null,
    title: 'Quality & Ingredients',
    description: 'We make no compromises when it comes to your health. We select only pharmaceutical-grade raw materials.',
  },
  card_1: {
    label: 'Efficacy',
    title: 'Standardized Extracts',
    description: 'We do not use plain plant powders but standardized extracts, guaranteeing exactly the amount of active substance your body needs.',
  },
  card_2: {
    label: 'Absorption',
    title: 'Liposomal Technology',
    description: 'We encapsulate sensitive nutrients in lipid spheres (liposomes) to protect them from stomach acid and increase their absorption rate.',
  },
  card_3: {
    label: 'Purity',
    title: 'Clean & Vegan',
    description: 'Our capsules are 100% plant-based. We exclude colorings, artificial flavorings, gluten and toxic preservatives from every formula.',
  },
  simple_section: {
    label: null,
    title: 'The science of absolute purity',
    description: 'The effectiveness of any supplement depends on the quality of the raw material. That is why, at Longevity Pharma, we work exclusively with certified suppliers and rigorously check every batch of ingredients.',
  },
};
