// Slug-urile englezesti, scrise manual (slug romanesc -> slug englezesc).
//
// Reguli: doar a-z, 0-9 si cratima. "&" este eliminat, nu transformat in "and".
// Cele patru perechi de produse cu nume identic (ashwagandha, cordyceps,
// resveratrol trans, rhodiola) primesc slug-uri distincte, pentru ca altfel
// s-ar suprascrie intre ele.

export const SLUG_PRODUSE = {
  'acid-alfa-lipoic': 'alpha-lipoic-acid',
  'acid-hialuronic': 'hyaluronic-acid-100mg',
  'aged-garlic': 'aged-garlic-extract',
  'aloe-vera': 'aloe-vera-extract',
  'alpha-gpc': 'alpha-gpc-300mg',
  'apigenin-aging': 'apigenin-sleep-aging',
  'ashwagandha-ksm': 'ashwagandha-ksm',
  'ashwagandha-ksm66': 'ashwagandha-ksm-66',
  'astaxantina': 'natural-astaxanthin-12mg',
  'astragalus-extract': 'astragalus-extract',
  'bacopa-monnieri': 'bacopa-monnieri',
  'berberina-hcl': 'berberine-hcl-500mg',
  'betaina-hcl': 'betaine-hcl-pepsin',
  'boswellia-serrata': 'boswellia-serrata',
  'carbune-activat': 'activated-charcoal',
  'ceai-verde-egcg': 'green-tea-extract-egcg',
  'celadrin': 'celadrin-extract',
  'colagen-bovin': 'grass-fed-bovine-collagen',
  'colagen-marine': 'marine-collagen-peptides',
  'colagen-peptide': 'collagen-peptides-hyaluronic-acid',
  'colagen-tip-2': 'undenatured-type-2-collagen',
  'complex-b-activ': 'active-b-complex',
  'complex-b-activat': 'activated-b-vitamin-complex',
  'coq10-kaneka': 'coq10-kaneka-200mg',
  'coq10-ubiquinol': 'coq10-ubiquinol-100mg',
  'cordyceps': 'cordyceps',
  'cordyceps-militaris': 'cordyceps-militaris',
  'creatina-creapure': 'creapure-creatine-monohydrate',
  'crema-arnica': 'arnica-joint-cream',
  'echinacea-forte': 'echinacea-forte',
  'enzime-digestive': 'digestive-enzyme-complex',
  'fisetin-extract': 'fisetin-100mg-extract',
  'gaba-500': 'gaba-500mg',
  'ginkgo-biloba': 'standardized-ginkgo-biloba',
  'ginkgo-biloba-ginseng-premium': 'ginkgo-biloba-ginseng-premium',
  'ginseng-panax': 'fermented-panax-ginseng',
  'glucozamina-condroitina': 'glucosamine-chondroitin',
  'glutation-lipozomal': 'liposomal-glutathione',
  'grape-seed': 'grape-seed-extract',
  'huperzine-a': 'huperzine-a',
  'imunity-complex': 'immunity-complex-360',
  'krill-oil': 'antarctic-krill-oil',
  'l-carnitina': 'liquid-l-carnitine',
  'l-glutamina': 'l-glutamine-powder-500g',
  'l-theanine-cofeina': 'l-theanine-natural-caffeine',
  'lions-mane-extract': 'lions-mane-extract',
  'maca-extract': 'gelatinized-peruvian-maca',
  'magneziu-bisglicinat': 'magnesium-bisglycinate',
  'magneziu-l-threonate': 'magnesium-l-threonate',
  'magneziu-malat': 'magnesium-malate',
  'melatonina': 'extended-release-melatonin',
  'milk-thistle': 'milk-thistle',
  'moringa': 'moringa-oleifera',
  'msm-pur': 'msm-methylsulfonylmethane',
  'multivitamine': 'multivitamin-complex',
  'mushroom-mix-long': 'longevity-mushroom-mix',
  'nac-cisteina': 'nac-n-acetyl-cysteine',
  'nad-booster': 'nad-booster-complex',
  'nad-spray': 'nad-nasal-spray',
  'nattokinaza': 'nattokinase',
  'nem-extract': 'eggshell-membrane-extract',
  'nmn-lipozomal': 'liposomal-nmn-500mg',
  'nmn-pur-500mg': 'pure-nmn-500mg-anti-aging',
  'nmn-puritate': 'nmn-99-purity',
  'nr-riboside': 'nr-nicotinamide-riboside',
  'olive-leaf': 'olive-leaf-extract',
  'omega-3-marin': 'concentrated-marine-omega-3',
  'omega-3-salbatic': 'wild-fish-oil-omega-3',
  'omega-3-sălbatic': 'omega-3-wild-fish-oil',
  'oregano-oil': 'wild-oregano-oil',
  'pachet-biohacker': 'beginner-biohacker-bundle',
  'pachet-femei': 'womens-bundle-collagen-d3-iron',
  'pachet-focus': 'unlimited-focus-bundle',
  'pachet-imunitate': 'iron-immunity-bundle',
  'pachet-somn-adanc': 'deep-sleep-bundle',
  'prebiotice': 'prebiotics-inulin-fos',
  'probiotice-50': 'probiotics-50-billion-cfu',
  'probiotice-femei': 'womens-probiotics-l-rhamnosus',
  'propolis-manuka': 'propolis-manuka-honey',
  'protocol-anti-aging': 'anti-aging-protocol',
  'protocol-articulatii': 'joint-recovery-protocol',
  'protocol-inima': 'cardiovascular-health-protocol',
  'pterostilbene': 'pterostilbene-50mg',
  'quercetin-bromelain': 'quercetin-bromelain',
  'quercetin-phyto': 'quercetin-phytosome',
  'quercetina-bromelaina': 'quercetin-with-bromelain',
  'reishi-extract': 'reishi-mushroom-extract',
  'resveratrol-pur': 'pure-resveratrol-99',
  'resveratrol-trans': 'trans-resveratrol',
  'resveratrol-trans-99': 'trans-resveratrol-99',
  'rhodiola-extract': 'rhodiola-extract',
  'rhodiola-rosea': 'rhodiola-rosea',
  'rodie-extract': 'standardized-pomegranate-extract',
  's-boulardii': 'saccharomyces-boulardii',
  'seleniu-organic': 'organic-selenium',
  'shilajit': 'purified-shilajit',
  'soc-negru': 'black-elderberry-extract',
  'sod-dismutaza': 'sod-superoxide-dismutase',
  'spermidina-extract': 'urolithin-a-500mg-extract',
  'spermidine-extract': 'ca-akg-longevity-complex',
  'turmeric-curcumin': 'turmeric-curcumin-95',
  'usturoi-negru': 'fermented-black-garlic',
  'valeriana-hamei': 'valerian-hops',
  'vit-c-lipozomal': 'liposomal-vitamin-c-1000mg',
  'vit-d3-k2': 'vitamin-d3-5000iu-k2',
  'vitamina-d3-k2-lipozomala': 'liposomal-vitamin-d3-k2',
  'vitamina-e-complex': 'vitamin-e-tocotrienol-complex',
  'vitc-siliciu': 'vitamin-c-silicon',
  'zeaxantina': 'zeaxanthin-lutein',
  'zinc-picolinat': 'zinc-picolinate-copper',
};

export const SLUG_CATEGORII = {
  'extracte': 'natural-extracts',
  'antioxidanti': 'antioxidants-nad',
  'focus': 'focus-memory',
  'colagen': 'collagen-joints',
  'probiotice': 'probiotics-digestion',
  'omega3': 'omega-3-fatty-acids',
  'longevitate': 'longevity-anti-aging',
  'energie': 'energy-vitality',
  'imunitate': 'immunity-protection',
  'vitamine': 'vitamins-minerals',
  'inima': 'heart-health',
  'somn-stres': 'sleep-stress',

  // Doua valori care apar in products.category_slug dar nu au rand in tabela
  // `categories` (11 produse). Nu strica nimic - lipseste doar firimitura cu
  // categoria pe pagina produsului - dar sunt tot text romanesc intr-un camp
  // folosit la potrivirea produselor similare, deci le traducem si pe ele.
  'esentiale': 'essentials',
  'pachete': 'bundles',
};

export const SLUG_JURNAL = {
  'cum-functioneaza-nmn-ul-la-nivel-celular': 'how-nmn-works-at-the-cellular-level',
  'colagen-hidrolizat-vs-colagen-nativ': 'hydrolyzed-vs-native-collagen',
  'protocol-reducere-inflamatie-stres-oxidativ': 'protocol-for-reducing-inflammation-and-oxidative-stress',
  'testare-lot-productie-laborator-tert': 'third-party-laboratory-batch-testing',
};

// Segmentele de ruta: folderul din app/ si, implicit, calea din URL.
export const RUTE = {
  'produs': 'product',
  'produse': 'products',
  'categorie': 'category',
  'jurnal': 'journal',
  'pachete': 'bundles',
  'abonamente': 'subscriptions',
  'calitate': 'quality',
  'despre-noi': 'about-us',
  'account/comenzi': 'account/orders',
  'account/adrese': 'account/addresses',
  'account/favorite': 'account/favorites',
  'account/facturi': 'account/invoices',
  'account/informatii': 'account/details',
  'account/plata': 'account/payment',
  'account/recenzii': 'account/reviews',
  'checkout/succes': 'checkout/success',
};
